apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todobackend
  name: todobackend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todobackend
  type: LoadBalancer
status:
  loadBalancer: {}
